Amelas22/DraftBot

commands.py

Adds an optional argument for displaying stats publically and defaults to ephemeral stats.

Make stats optionally ephemeral

---

bot.py
services/draft_setup_manager.py

Some logging improvements and making the draftmancer retry import and wait for 2 users before disconnecting.

logging improvement and bug fix for draftmancer import

---

bot.py
cogs/admin_commands.py
cogs/draft_commands.py

- Refactored bot commands into a cog-based structure for better organization and modularity
- Added new admin commands for dynamic extension management:
- `/reload` - Reload a specific extension
- `/load` - Load a new extension
- `/unload` - Unload an extension
- `/reloadall` - Reload all extensions
- Implemented a Bot Manager role system for delegating bot management permissions
- `/setup_bot_manager` - Creates the Bot Manager role
- `/add_bot_manager` - Grants Bot Manager permissions to users
- `/remove_bot_manager` - Removes Bot Manager permissions
The new extension management system allows for hot-reloading of bot features, which means:
- Changes can be applied without restarting the bot
- Faster development and testing cycles
- Zero downtime updates for most changes
- Ability to …

refactor commands to cogs and add admin controls

---

session.py

This PR removes the deprecated `re_register_views` function from `session.py`. The function has been superseded by a more comprehensive implementation in `utils.py` that handles multiple draft stages and view types.
- Remove deprecated `re_register_views` function from `session.py`
- The active implementation in `utils.py` remains unchanged and continues to handle:
- Initial draft stages
- Team selection stages
- Pairing stages
- Winston drafts
- Match result buttons
- Eliminates duplicate code that could cause confusion
- Removes simpler implementation that only handled basic cases
- Maintains single source of truth for view re-registration logic
- Prevents potential conflicts between implementations

remove unused code

---

services/draft_setup_manager.py

Change delay on log release to 2h per feedback from mack

change delay to 2h per feedback from mack

---

views.py

This PR refactors the `views.py` file to improve code organization and maintainability by breaking down the complex `add_buttons` method into smaller, more focused methods.
- Split the monolithic `add_buttons` method into several smaller, purpose-specific methods:
- `_add_signup_buttons`: Handles sign-up related buttons
- `_add_shared_buttons`: Manages buttons common across all session types
- `_add_winston_specific_buttons`: Handles Winston draft specific buttons
- `_add_premade_buttons`: Manages premade draft specific buttons
- `_add_generic_buttons`: Handles buttons for other draft types
- `_apply_stage_button_disabling`: Manages button state based on session stage
- Added a helper method `_add_button` to reduce code duplication
- Improved button state management with a more readable …

refactor views.py for cleanliness

---

bot.py
cogs/leaderboard.py
services/leaderboard_formatter.py
services/leaderboard_service.py

This PR refactors the leaderboard system to improve code organization, maintainability, and extensibility. The changes split the monolithic leaderboard code into separate service and formatter modules while maintaining all existing functionality.
- Split leaderboard functionality into three distinct modules:
- `leaderboard.py` (Cog): Handles Discord bot commands and UI interactions
- `leaderboard_service.py`: Contains core data processing and business logic
- `leaderboard_formatter.py`: Manages embed creation and display formatting
- Added proper error handling for leaderboard refresh operations
- Improved code organization with clear separation of concerns
- Added type hints and docstrings for better code documentation
- Centralized configuration for leaderboard categories and timeframes …

refactor leaderboard for extensibility

---

views.py

Adds automatic room creation and pairings for draft sessions after a 10-minute countdown. When teams are formed, the system now:
1. Schedules rooms and pairings to be automatically created after 10 minutes
2. Displays a countdown timer in the team announcement embeds
3. Creates a background task to handle the automatic creation process
The feature can be overridden by manually clicking the "Create Rooms & Pairings" button, which cancels the scheduled automatic task. Auto-pairings tasks are also properly cleaned up when drafts are canceled.

Auto Create Draft Rooms auto-draft-rooms

---

views.py

Added automatic draft setup manager initialization when teams are randomized.
- Added code to automatically initialize or update the DraftSetupManager when teams are randomized
- Implemented the same logic in two places to handle both early return and normal flow paths
- Added error handling to prevent disruption of the normal team randomization process
- Added logging to track manager state during team creation
1. Create a draft session and add players
2. Randomize teams using the button
3. Verify that a DraftSetupManager is created automatically
4. Check logs to confirm the manager is properly tracking the session state
5. Verify that the seating order process begins automatically
Previously, the draft setup process required manual intervention after teams were created. This change …

fix for dm full prior to team creation

---

views.py

Extracted common room creation and pairings logic into a reusable helper method to reduce code duplication.
- Created a new `_create_rooms_pairings` helper method that contains the shared logic for creating rooms and posting pairings
- Refactored both `auto_create_rooms_pairings` and `create_rooms_pairings_callback` to use this common helper method
- Simplified error handling and processing flag management
- Added a distinction in the chat message between auto-created and manually created pairings
- Improved variable scoping by consistently using the session_id parameter
The previous implementation had significant code duplication between the automatic and manual room creation methods. This refactoring improves maintainability by centralizing the core logic, making future changes easier …

refactor of room creation

---

services/draft_setup_manager.py

Consolidated process completed by DraftLogManager to DraftSetupManager.

consolidate datacollections with draft setup manager

---

services/draft_setup_manager.py
views.py

Commented out creation of DraftLogManager functionality during room creation.
The DraftLogManager is no longer required as its functionality was included in DraftSetupManager

remove legacy calls to datacollections

---

cogs/draft_control.py
services/draft_setup_manager.py

Improved draft cancellation flow and automated log collection with disconnection after draft completion.
- Fixed the draft cancellation process by properly marking drafts as cancelled to skip log collection
- Added automatic disconnection after successful log collection (10 seconds delay)
- Removed the complex ownership transfer logic from the disconnection process
- Added monitoring to detect when drafts end and trigger log collection automatically

reconfigured disconnect safely

---

services/draft_setup_manager.py

fix for picktimer

---

views.py

fix indent

---

views.py

remove legacy DraftLogManager from create-rooms method

---

fix.py

fix error in draft session 416632328715239434-1744767391

fix db error

---

services/draft_setup_manager.py
views.py

Improved room creation logic to prevent duplicate rooms and provide better feedback when a draft ends.
- Added a check to verify if rooms already exist before attempting to create new ones
- Enhanced error handling in the room creation process
- Added appropriate user feedback when rooms already exist or when creation fails
- Modified the draft end handler to check the result of room creation and provide appropriate messages
- Fixed a UI update issue after room creation attempts
This change prevents the creation of duplicate rooms when a draft ends or when a user manually triggers room creation. It also improves the user experience by providing clear feedback about the status of room creation, whether successful, already done, or failed.

fix to duplicate room creation

---

reconnect_drafts.py

recoonect draft sessions

---

modals.py
views.py

add mocs vintage cube

---

views.py

Added player count validation to ready check functionality.
- Moved the database fetch for the draft session earlier in the ready check callback function
- Added validation to ensure ready checks can only be initiated when there are exactly 6, 8, or 10 players in the queue
- Shows an error message to users who attempt to start a ready check with an invalid number of players
The draft system is designed to work optimally with specific player counts (6, 8, or 10). This validation prevents users from starting ready checks with incompatible numbers of players, which could lead to unbalanced teams or other gameplay issues.

ready check requires 6, 8, or 10 users to fire

---

services/draft_setup_manager.py

Improved the ready check system to continue tracking user readiness after timeout and automatically restart when all users become ready.
- Extended the ready check timeout from 60 to 90 seconds
- Added a `post_timeout_ready_users` set to track readiness after a timeout occurs
- Modified `handle_user_ready_update()` to process ready state changes even when no active ready check is running
- Enhanced the timeout message to show which users are still not ready
- Implemented auto-restart of ready check when all users become ready after a timeout
This improves the user experience by eliminating the need for manual ready check restarts when users are late. The system now continues tracking readiness after a timeout and automatically initiates a new ready check when everyone is ready, reducing …

adjust DM ready check logic to track stale readys

---

services/draft_setup_manager.py
utils.py

Implemented a system to automatically unlock draft logs when a match victory or draw is determined.
- Added a new `current_draft_log` property to store the draft log data
- Created a listener to capture draft logs as they come in
- Implemented a `manually_unlock_draft_logs()` method that can force logs to be public
- Increased the draft log unlock timer from 120 to 180 minutes
- Integrated log unlocking with the victory/draw determination process
- Commented out the old scheduled log collection code that is now replaced by this more reliable approach
1. Start a draft and complete it
2. When a victory or draw is determined, verify that draft logs are automatically unlocked
3. Check that logs are accessible immediately after the match result is posted
4. Verify the logs are properly shared …

unlock draftlogs after victory screen

---

views.py

- Replaced manual embed generation with `update_draft_message` function call
- Removed redundant logging statements
- Improved code comments for clarity
- Simplified the test users callback by leveraging existing functionality
This refactoring:
- Reduces code duplication by using the shared `update_draft_message` function
- Makes the code more maintainable by removing redundant embed generation logic
- Improves consistency by using the same message update mechanism as other features
- Reduces the risk of bugs by using a well-tested shared function
- The functionality remains exactly the same
- Test users are still properly added and displayed
- The draft message updates correctly with the new participants
- All stake information is properly created and stored

refactor for cleanliness

---

services/draft_setup_manager.py

- Centralized ready check instructions into a constant
- Updated all ready check messages to use consistent instructions
- Improved clarity of instructions for users
- Added `READY_CHECK_INSTRUCTIONS` constant at the top of the file
- Updated all message templates to use the centralized instructions
- Maintained consistent messaging across different ready check states
This change improves user experience by providing clear, consistent instructions across all ready check states, making it easier for users to understand what actions they can take during the ready check process.

update ready instructions

---

services/draft_setup_manager.py

- Added automatic ready check invalidation when users join or leave during an active ready check
- Implemented proper handling of user state changes during ready checks
- Added detailed logging for user join/leave events during ready checks
- Improved error handling and message updates for ready check failures
- Added automatic restart of ready checks when all players are present
- Added new `invalidate_ready_check` method to handle user state changes
- Improved message handling to update existing messages when possible
- Added better error handling and logging throughout the ready check process
- Implemented automatic restart of ready checks when conditions are met
This change improves the user experience by automatically handling user state changes during ready checks, reducing the need …

automatically retrigger ready check when user leaves and rejoins

---

views.py

Added detailed logging to the ready check and team creation processes to improve debugging capabilities.
- Extended the ready check session timeout from 10 minutes to 30 minutes
- Added comprehensive logging throughout the ready check and team creation flows
- Improved error handling in the cleanup process
- Added session dictionary state logging to help track session lifecycle
- Fixed code indentation in the `randomize_teams_callback` method
- Added informative log messages for session verification and team creation steps
1. Initiate a ready check for a staked draft
2. Create teams for the draft
3. Check server logs for the new detailed logging messages
4. Verify that sessions remain valid for 30 minutes instead of 10 minutes
This change addresses debugging challenges when …

increasing timeout for ready check to 30 min for draft session

---

services/draft_setup_manager.py

code clean up

---

services/draft_setup_manager.py

Consolidate all imports at the top of draft_setup_manager.py, removing redundant imports that were scattered throughout the file. This improves code maintainability and follows Python best practices.

clean up imports

---

views.py

Improved draft cancellation process by properly cleaning up draft manager resources.
- Added proper cleanup of active draft managers when a draft is cancelled
- Added logging throughout the cancellation process for better debugging
- Implemented a method to mark drafts as cancelled to prevent log collection
- Added verification that managers are properly removed from the active managers registry
- Ensured draft managers are safely disconnected from Draftmancer
1. Start a draft session
2. Cancel the draft using the "Yes, Cancel Draft" button
3. Verify in logs that the draft manager is properly disconnected
4. Confirm the draft session is removed from the database
5. Check that no orphaned draft managers remain in the ACTIVE_MANAGERS registry
Previously, when drafts were cancelled, the …

bot now disconnects from draftmanacer after cancel draft is confirmed

---

services/draft_setup_manager.py

Added automatic removal of unexpected users from draft sessions and fixed ready check invalidation when users join during an active check.
- Added logic to invalidate ready checks when users join during an active ready check
- Implemented automatic detection and removal of unexpected users who join a draft session
- Added a 5-second warning before removing unexpected users
- Replaced direct Discord client references with `get_bot()` function calls
- Fixed user tracking to properly identify unexpected users
1. Start a draft session with a specific set of expected users
2. Have an unexpected user join the session and verify they receive a warning message and are removed after 5 seconds
3. Start a ready check and have a new user join during the check to verify it gets invalidated
4. Verify …

remove unexpected users after teams are made

---

services/draft_setup_manager.py

Improved handling of unexpected users in draft sessions to prevent race conditions and ensure proper seating order.
- Added a `removing_unexpected_user` flag to prevent triggering ready checks while removing an unexpected user
- Modified the `handle_unexpected_user` method to properly set and reset this flag
- Added a delay in seating order attempts when an unexpected user is being removed
- Added a post-removal check to verify if all expected users are present after an unexpected user is removed
- Implemented proper cleanup in a `finally` block to ensure the flag is always reset
- Added a brief delay after user removal to ensure changes are processed
1. Start a draft session with a specific number of expected users
2. Have an unexpected user join the session
3. Verify the unexpected user …

update timing issue when user joins unexpectedly

---

bot.py
reconnect_drafts.py

Improved draft reconnection process by implementing sequential processing with delays between connections to prevent rate limiting.
- Replaced concurrent task execution with sequential processing for draft reconnections
- Added a 3-second delay between each connection to avoid overwhelming the API
- Delayed log collection by 65 seconds after bot startup to ensure proper initialization
- Modified `reconnect_draft_setup_sessions` and `reconnect_recent_draft_sessions` to return manager objects instead of tasks
- Implemented a new `monitor_reconnection_tasks` function that processes managers sequentially
- Moved draft log collection reconnection into a separate delayed task
1. Restart the bot and observe the logs for sequential reconnection messages
2. Verify that draft setup reconnections …

add delays for bot restart to avoid rate limiting

---

services/draft_setup_manager.py

Improved WebSocket connection handling for draft setup manager to ensure more reliable connections and proper disconnection when logs are collected.
- Replaced the `connect_with_retry` method with direct connection logic
- Added a check to disconnect existing connections before attempting a new one
- Enhanced the draft completion logic with better state tracking
- Added a draft ended time tracking mechanism to properly handle the end of drafts
- Implemented a break statement to exit the loop when logs are collected successfully
1. Start a draft and verify the connection is established properly
2. Test reconnection by temporarily disrupting the connection
3. Complete a draft and verify logs are collected successfully
4. Verify the connection is properly closed after logs collection
The …

revert keep_connection_alive

---

cogs/draft_control.py

Added a new `/replace_with_bots` command that allows draft participants to vote on replacing disconnected players with bots.
- Added a new `ReplaceWithBotsVoteView` class that handles the voting UI and logic
- Implemented the `/replace_with_bots` slash command that initiates a vote
- Added tracking for active replacement votes using `ACTIVE_REPLACE_VOTES` dictionary
- Updated the pause command message to inform users about the new replacement option
- The vote requires more than half of participants to vote "yes" to pass
- When passed, the system automatically replaces disconnected players with bots
1. Start a draft and have all players join
2. Use `/pause` to pause the draft
3. Have one or more players disconnect
4. Use `/replace_with_bots` to initiate a vote
5. Have participants vote …

add replace_with_bots command

---

views.py

Replaced the Ready Check system with a voting mechanism that allows players to decide whether to fire a draft with the current number of players or wait for more.
- Transformed the Ready/Not Ready buttons into Fire/Wait voting buttons
- Added automatic team creation when a majority votes to fire the draft
- Implemented vote counting logic with required thresholds based on queue size
- Created a shared team creation handler that works for both manual and automatic triggers
- Updated embed displays to show voting status and progress toward required majority
- Removed cooldown system that was previously limiting ready check frequency
- Consolidated code by creating a reusable team creation function
1. Join a draft session with 6 or 8 players
2. Initiate a ready check
3. Verify the new voting …

auto create teams when ready check passes

---

views.py

Added checks to prevent teams from being created multiple times for the same draft session.
- Added validation in the `randomize_teams_callback` function to check if teams have already been created before proceeding
- Enhanced the `handle_vote` function to detect if teams were already created manually before auto-creating teams
- Added a similar check in the `auto_create_teams` method as an additional safeguard
- Improved cleanup of session data after votes are completed
1. Start a draft session and manually create teams
2. Try to create teams again using the button or through the voting system
3. Verify that you receive an error message indicating teams have already been created
4. Check logs to confirm the duplicate team creation was prevented
This prevents a race condition where teams …

add check to ensure teams are not created twice

---

views.py

Enhanced the ready check system with better UI labels, error handling, and validation for queue participants.
- Added special UI labels for 10-player queues, showing "🔥 Fire on 10" and "❌ Not Ready" buttons
- Improved error message when no active ready check is found
- Added validation to ensure voters are still in the queue before proceeding
- Added proper error handling during team creation
- Ensured session cleanup happens even when errors occur
- Added more descriptive messages when aborting team creation
1. Start a draft session with 10 players and verify the button labels are correct
2. Test the ready check system with players joining/leaving during voting
3. Verify error messages appear correctly when a ready check is no longer active
4. Test edge cases where voters are no longer …

improvements to ready check

---

views.py

Added a new "Either Option" button to the ready check voting system that counts toward the "fire" threshold while giving players more flexibility in their voting preferences.
- Added a new "Either Option" button to the ready check UI
- Players can now vote for "Either Option" which counts toward the fire threshold
- Updated the vote counting logic to include "either" votes when determining if there's a majority
- Enhanced the status display to show progress toward firing and separate vote counts
- Improved the results message to show the breakdown of votes (fire, either, wait)
- Added additional logging for vote details
1. Start a draft session and trigger a ready check
2. Verify the new "Either Option" button appears alongside Fire and Wait
3. Have players vote using the new button and …

added either option button to ready check vote

---

views.py

Improved the voting logic for draft sessions to consider both "fire" and "wait" preferences when counting "either" votes.
- Updated the vote counting logic to consider "either" votes for both "fire" and "wait" options
- Added a new condition where even if there are enough votes to fire, the session will wait if more players prefer waiting
- Enhanced the status messages to show more detailed vote counts and clearer explanations
- Improved the embed display to show both effective fire and wait vote totals
- Updated the success message to clarify that firing happens when more players prefer to fire now
1. Start a draft session with fewer than the target number of players
2. Trigger a ready check vote
3. Have players vote with different combinations of "fire", "wait", and "either"
4. Verify …

rework either option logic

---

views.py

revert prior changes to ready check

revert readycheck changes

---

bet_analysis.py

Improved bet analysis to only count users who stayed in drafts when analyzing 10 tix max stakes.
- Modified `get_last_ten_10tix_max_stakes()` to filter out users who left drafts before completion
- Updated `get_additional_stats()` to only count users who remained in the sign_ups dictionary
- Added new statistics showing the difference between users who set 10 tix max stake but left vs. those who stayed
- Added return value to `get_last_ten_10tix_max_stakes()` for use in additional stats
- Improved output formatting with clearer labels and wider separator lines
1. Run the `main()` function to execute both analysis functions
2. Verify that the output now only includes users who set max stake to 10 tix AND stayed in the draft
3. Check the new statistics showing the percentage of 10 tix users …

bug fix to 10 tix analysis

---

views.py

Users would intermittently get stuck where clicking "Create Teams" showed "Teams are already being created. Please wait." but no teams were created. Sessions became permanently unusable until creating a new draft.
The team creation process uses `PROCESSING_TEAMS_CREATION[session_id] = True` to prevent race conditions. However, if database/Discord API failures occurred during initial validation (before reaching the main try/finally block), the processing flag would never get cleaned up, leaving it permanently stuck.
Extended the try/finally block to encompass all operations after setting the processing flag, ensuring cleanup happens regardless of where failures occur.
- Added helper functions: `_validate_team_creation_request()` and `_validate_staked_draft_requirements()`
- Consolidated …

better error handling and refactor

---

cube_views/CubeSelectionView.py
helpers/utils.py
modals.py

missed a spot

---

cogs/ping_cooldown.py
database/message_management.py
models/__init__.py
models/draft_logs.py
models/draft_session.py
models/match.py
models/player.py
models/stake.py
models/team.py
preference_service.py

- Synchronize SQLAlchemy models with the actual database schema
- Fix column type mismatches and constraints across multiple models
- Update import statements and model relationships for consistency
- **Models Updated**: `draft_logs.py`, `draft_session.py`, `match.py`, `player.py`, `stake.py`, `team.py`
- **Database Layer**: Updated `message_management.py` for proper model usage
- **Service Layer**: Enhanced `preference_service.py` with improved error handling
- **Cogs**: Updated `ping_cooldown.py` for model compatibility
- Fixed column type definitions to match actual database schema
- Updated nullable constraints and default values
- Improved model relationships and foreign key references
- Enhanced type hints and model imports
**Low Risk** - This is a schema alignment change that …

update model to reflect db

---

models/sign_up_history.py
test_signup_history.py

This commit introduces helper functions and infrastructure for the SignUpHistory model, including a new class method for recording signup events and comprehensive test coverage.
- **New Class Method**: Added `SignUpHistory.record_signup_event()`
- Generates unique UUIDs for each signup event record
- Handles both 'join' and 'leave' actions
- Async database integration with proper session management
- Takes parameters: `session_id`, `user_id`, `display_name`, `action`, `guild_id`
- Added `import uuid` for unique ID generation
- Added `from database.db_session import db_session` for async database operations
- Implemented proper async context management for database transactions
```python
@classmethod
async def record_signup_event(cls, session_id: str, user_id: str, display_name: str, …
```

add helper functions for sign up history
