cogs/draft_commands.py
session.py

This PR adds a new `/report` command that allows users to report match results directly from draft channels. It also introduces a significant improvement to our database access patterns by implementing a context manager and adding model-based query methods.
- Added a slash command that lets users report their match results from any draft channel
- Command automatically finds the user's earliest unreported match
- Uses the existing `MatchResultSelect` UI component for consistent user experience
- Added `db_session()` context manager to handle session lifecycle and transaction management
- Implemented model-based query methods:
- `DraftSession.get_by_channel_id()`
- `DraftSession.get_by_session_id()`
- `DraftSession.is_user_participating()`
- `MatchResult.find_unreported_for_user()`
- …

03 16 add report slash command for easier reporting

---

services/draft_setup_manager.py

Feedback from users indicated that they would prefer the default draft timer to be 60s instead of 75s. This change reflects that.

update pick timer to 60 based on feedback from LSV and others

---

bot.py
cogs/draft_commands.py
commands.py
modals.py
sessions/winston_session.py
utils.py
views.py

- Removed old inconsistent `winstondraft` command
- Added new `/winston_draft` command to align with other command naming conventions
- Updated cube selection list for Winston drafts to include:
- LSVWinston
- ChillWinston
- WinstonDeluxe
- data
- Updated command registration in `DraftCommands` cog
- Added Winston-specific cube options to `CubeDraftSelectionView`
- Ensured proper session type handling in session creation flow
- Maintained consistent error handling with other draft commands
- Verified command registration and visibility in Discord
- Tested cube selection menu population
- Confirmed Winston draft session creation
- Validated session type handling
- Fixes inconsistent command naming
- Improves user experience with curated Winston cube list

refactor winston draft command

---

config.py
database/message_management.py

- Renamed `find_cube_drafters_role` to `find_session_role` to support different roles per session type
- Added session role configuration to default and special guild configs
- Enhanced role lookup to fall back to default drafter role if no session-specific role is configured
- Added detailed logging to help diagnose role lookup issues
Currently, all draft notifications mention the same role regardless of session type. This change allows for more targeted notifications - for example, mentioning "Winston Gamers" for winston drafts or "Cube Drafters" for staked drafts.
Default session role mapping:
```json
"session_roles": {
"winston": "Winston Gamer",
"random": "Cube Drafter",
"premade": "Cube Drafter"
}

update to notify relevant role based on session type

---

config.py
datacollections.py
league.py
models/session_details.py
reconnect_drafts.py
services/draft_setup_manager.py

- Centralized Draftmancer URL configuration by introducing a base URL constant
- Added helper functions for generating different types of Draftmancer URLs
- Updated all hardcoded Draftmancer URLs to use the new configuration system
- Set default environment to beta.draftmancer.com
- Added `DRAFTMANCER_BASE_URL` constant in `config.py`
- Created new helper functions:
- `get_draftmancer_base_url()`
- `get_draftmancer_session_url()`
- `get_draftmancer_draft_url()`
- `get_draftmancer_websocket_url()`
- Updated URL references across multiple files:
- `datacollections.py`
- `league.py`
- `models/session_details.py`
- `reconnect_drafts.py`
- `services/draft_setup_manager.py`
- Easier environment switching (prod/beta/dev)
- Reduced code duplication
- More maintainable URL management
- Consistent …

refactor base draftmancer url

---

league.py
sessions/base_session.py
utils.py
views.py

- Removed generic draft links from initial session embeds
- Added personalized draft links for each user in various UI components
- Updated reminder system to send personalized draft links
- Enhanced ready check system with personalized links
- Modified `BaseSession` to remove generic draft link from common description
- Updated `generate_ready_check_embed` to support personalized links
- Enhanced channel embeds to display personalized links for each user
- Updated reminder system in `utils.py` to send individual links
- Modified league challenge view to use personalized links
- Added "Your Personalized Draft Links" field in ready check embeds
- Updated team announcement embeds with personalized links
- Enhanced reminder messages with clickable personalized links
- Improved Swiss draft …

display personalized draft links

---

services/draft_setup_manager.py
sessions/swiss_session.py
sessions/winston_session.py
views.py

This PR introduces several improvements to the DraftBot system, focusing on Winston draft support and enhanced connection management.
1. **Winston Draft Support**
- Added a "Start Draft" button for Winston drafts
- Implemented team formation and seating order management
- Created personalized draft links for participants
- Added visual team assignments (Red vs Blue teams)
2. **Connection Management Improvements**
- Modified DraftBot to connect as a spectator instead of a player
- Added connection state tracking with proper locking mechanisms
- Improved user counting to exclude bot from player counts
- Enhanced seating order management with retry logic
3. **Code Cleanup**
- Removed obsolete buttons from Swiss and Winston session classes
- Improved error handling and logging throughout the …

04 09 remove obsolete buttons

---

scripts/cleanup_merged_branches.sh

This PR adds a new shell script `cleanup_merged_branches.sh` that helps maintain a clean git repository by identifying and removing branches that have been fully merged into the main branch.
- Automatically detects the main remote and branch (supports both `main` and `master` naming conventions)
- Falls back to user input if automatic detection fails
- Safely identifies branches that are fully merged into the main branch
- Interactive confirmation before deleting each branch
- Provides a summary of deleted branches at the end
1. Make the script executable: `chmod +x scripts/cleanup_merged_branches.sh`
2. Run the script: `./scripts/cleanup_merged_branches.sh`
3. Follow the interactive prompts to confirm branch deletions
- Helps maintain a clean repository by removing unnecessary branches
- …

adding a script to cleanup merged branches

---

helpers/utils.py
services/draft_setup_manager.py
sessions/base_session.py
sessions/premade_session.py
sessions/random_session.py
sessions/staked_session.py
sessions/swiss_session.py
views.py

This PR adds the ability to change the cube during an active draft session through a new "Update Cube" button. This feature allows draft organizers to switch cubes without having to restart the entire draft session.
- Added a new "Update Cube" button to the draft interface
- Created a cube selection dropdown with predefined cube options
- Implemented cube thumbnail management through a new `helpers/utils.py` module
- Added cube update functionality to `DraftSetupManager`
- Improved embed message structure to better display cube information
- Added global manager registry to track active draft sessions
- Created `CUBE_THUMBNAILS` mapping for consistent cube thumbnails
- Added `update_cube` method to `DraftSetupManager` for handling cube changes
- Implemented `CubeUpdateSelectionView` for …

add button to change cube

---

cogs/draft_control.py
services/draft_setup_manager.py

Added a `/scrap` command that allows draft participants to vote on canceling a paused draft, and improved the time display in ready checks.
- Added a new `/scrap` slash command that initiates a vote to cancel an ongoing draft
- Created a `ScrapVoteView` class to handle the voting UI and logic
- Improved time display in ready checks to use Discord's relative timestamp format (`<t:timestamp:R>`)
- Changed time tracking from `asyncio.get_event_loop().time()` to `datetime.now()`
- Extended the ready check timeout from 30 to 60 seconds
- Updated the pause command message to inform users about the `/scrap` option
1. Start a draft and use `/pause` to pause it
2. Use `/scrap` to initiate a cancellation vote
3. Have participants vote using the Yes/No buttons
4. Verify the vote passes if more than …

Add Scrap Command and fix timeout timers

---

cogs/draft_control.py
services/draft_setup_manager.py

Added a GIF to the mutiny command and implemented seating verification before ready checks.
- Added a Tenor GIF link to the mutiny command message for a more engaging user experience
- Implemented a new `verify_seating_order` method that runs before ready checks to ensure players are seated correctly
- The seating verification process:
- Fetches the desired seating order from the database if not already stored
- Checks if all expected users are present in the session
- Forces a reset of the seating order to ensure correctness
- Provides detailed error messages if verification fails
1. Test the mutiny command to see the Jack Sparrow GIF appear with the mutiny message
2. Test the ready check process with:
- A complete set of players to verify seating works correctly
- Missing players to see …

Add seating order verifiction or reset before ready check

---

cogs/draft_control.py

Improved draft cancellation UX with clearer messaging and added `/mutiny` command reference.
- Set `manager.drafting = False` when a scrap vote passes
- Enhanced the draft cancellation message to include information about the `/mutiny` command
- Improved formatting of messages with line breaks for better readability
- Updated the failed vote message formatting
1. Start a draft session
2. Run the `/scrap` command to initiate a vote to cancel the draft
3. Verify that when the vote passes:
- The draft is properly canceled
- The final message includes information about both `/ready` and `/mutiny` commands
4. Verify that when the vote fails:
- The message correctly instructs to use `/unpause` to continue
This change improves user experience by setting the drafting state correctly and providing …

fix for drafting variable on scrap success

---

cogs/draft_control.py
services/draft_setup_manager.py

Fixed draft cancellation logic and reduced pick timer to 1 second.
- Added a `draft_cancelled` flag to track when drafts are manually cancelled
- Added a handler for the `endDraft` event to properly detect when drafts end
- Modified the scrap command to mark drafts as cancelled before stopping them
- Added a `mark_draft_cancelled()` method to the DraftSetupManager
- Reduced the pick timer from 60 seconds to 1 second
1. Start a draft and use the scrap command to cancel it
2. Verify that the cancellation is properly handled without duplicate messages
3. Start a new draft and verify the pick timer is set to 1 second (TESTING ONLY)
4. Let a draft complete naturally and verify it's properly detected as completed
The previous implementation didn't properly distinguish between drafts that were …

initial endDraft listener

---

views.py

Added error handling for Discord message update failures in team randomization.
Added try-except blocks around `interaction.response.edit_message()` calls in the `randomize_teams_callback` function to catch and log any exceptions that occur when updating Discord messages. This prevents the application from crashing when message updates fail.
Discord interactions can sometimes fail due to network issues, permission changes, or message deletion. This change improves application resilience by gracefully handling these failures instead of crashing, while also providing useful error logs for troubleshooting.

add exception reporting to edit draft msg to team msg

---

models/draft_session.py
services/draft_setup_manager.py
update_schema.py
views.py

Added Discord status message tracking for Draftmancer sessions to provide real-time updates on player presence.
- Added `status_message_id` column to the `DraftSession` model to store the ID of the status message
- Implemented status message functionality in `DraftSetupManager` that shows:
- Players present in the Draftmancer session
- Players who are missing
- Any unexpected users who joined
- Instructions for the draft process
- Added automatic status message updates when users join or leave the session
- Enhanced seating order logic to only proceed when all expected users are present
- Added more detailed error messages when ready checks or seating orders fail
- Created database migration script to add the new column
This change improves the user experience by providing clear, …

Add msg that updates when users join leave session

---

views.py

Improved button disabling logic in draft sessions to prevent creating rooms when a draft manager is already active.
- Modified the button disabling logic in the draft session UI to check if a draft session ID exists in `ACTIVE_MANAGERS` before enabling the "Create Rooms" button
- Updated the `_apply_stage_button_disabling` method to conditionally disable the "Create Rooms" button based on manager status
- Applied the same conditional logic in the `randomize_teams_callback` method to maintain consistent button states
This change prevents users from attempting to create rooms when a draft manager is already active for that session, avoiding potential conflicts or race conditions. It provides better visual feedback to users about the current state of the draft session and which actions are …

disable create rooms button

---

player_stats.py

Updated player statistics queries to use `teams_start_time` instead of `draft_start_time`.
Modified all SQL queries in the player statistics module to reference `teams_start_time` instead of `draft_start_time` when filtering and ordering draft sessions. This change affects:
- Player statistics retrieval
- Trophy queries
- Head-to-head statistics
- Display name fuzzy matching
The `teams_start_time` field more accurately represents when a draft session becomes active for statistical purposes. This ensures that player statistics are calculated based on the correct timestamp, providing more accurate data for time-based filtering and sorting.

C:/Program Files/Git/stats fix to use teams_start_time

---

modals.py

Updated the display name for the APR25 cube option in dropdown menus.
Changed the label for the APR25 cube option from "APR25" to "2025 MOCS Vintage Cube" in one location and from "MOCS Vintage Cube" to "2025 MOCS Vintage Cube" in another location. The value remains "APR25" in both instances.
This change provides a more descriptive and consistent label for the APR25 cube across the application, making it clearer to users what this cube option represents. The standardized naming improves user experience by using the official cube name rather than an internal code.

fix mocs name for random sessions

---

analysis.py
draft.py

Added guild-specific filtering to stake analysis and created a new script to analyze win rates based on stake amounts.
- Modified `StakeAnalyzer` to accept a guild ID parameter and filter results by guild
- Added a constant `TARGET_GUILD_ID` to specify the guild to analyze
- Updated output file names and log messages to include guild ID
- Created a new `draft.py` script that analyzes win rates for different stake amounts (10, 20, 50, 100, >100)
- The new script tracks wins and losses for each stake category and calculates win rates
1. Run the updated analysis script:
```
python analysis.py
```
2. Run the new win rate analysis script:
```
python draft.py
```
3. Check the generated output files:
- `stake_analysis_guild_1355718878298116096_*.csv`
- `stake_winrate_analysis_*.txt`
To enable …

analysis queries

---

sessions/base_session.py
utils.py
views.py

Adds functionality to automatically cancel draft queues that have been inactive for 90 minutes.
- Changed the deletion time for new draft sessions from 3 days after start to 90 minutes from creation
- Added logic to reset the deletion timer whenever a user signs up for a draft
- Implemented cleanup logic to cancel and remove inactive draft queues
- Increased the frequency of the cleanup task from hourly to every 10 minutes
1. Create a new draft queue
2. Verify that no users sign up for 90 minutes
3. Confirm the queue is automatically cancelled with a message indicating inactivity
4. Create another queue and have a user sign up after 80 minutes
5. Verify the queue remains active for another 90 minutes
This change prevents stale draft queues from lingering in channels when there's …

remove queues due to inactivity

---

utils.py

Fixed a bug in the queue cancellation notification logic by properly indenting code blocks.
Fixed an indentation issue in the `cleanup_sessions_task` function where the `msg.delete()` and `logger.info()` calls were incorrectly indented. These operations are now properly nested inside the `if msg:` condition, ensuring they only execute when a message exists.
The previous indentation caused the code to attempt to delete messages and log information even when no message existed (`msg` was None), potentially leading to errors. This fix ensures these operations only run when a valid message is available, preventing potential exceptions.

second fix for cleanup logic

---

config.py

Updated the Draftmancer base URL from beta to production.
Changed `DRAFTMANCER_BASE_URL` from `https://beta.draftmancer.com` to `https://draftmancer.com`, switching the application from using the beta environment to the production environment.
1. Run the application with the updated configuration
2. Verify that API calls are correctly routing to the production environment
3. Confirm that all functionality works as expected with the production endpoint
The beta testing phase has concluded, and the application is now ready to use the production environment. This change ensures users interact with the stable production API rather than the beta testing environment.

change to draftmancer production

---

services/draft_setup_manager.py

Increased the delay before log collection from 5 to 60 seconds.
Modified the `schedule_log_collection` delay parameter in the `on_draft_log_response` method from 5 seconds to 60 seconds, giving the system more time before attempting to collect logs.
1. Trigger a draft log response scenario
2. Verify that log collection now starts after a 60-second delay instead of 5 seconds
3. Confirm that the logs are still collected correctly despite the longer delay
The increased delay likely provides more time for all relevant logs to be generated and stabilized before collection begins. This could improve the completeness of collected logs and reduce the chance of missing important information that might appear shortly after the initial response.

fix to db crashes on log collection

---

cogs/draft_logs_cog.py
models/__init__.py
models/draft_logs.py
update_schema.py

Added a new Draft Logs system that allows users to submit MTG draft logs anonymously and have them posted on a schedule.
- Created a new `DraftLogsCog` with commands for setting up draft log channels
- Added database models for log channels, backup logs, user submissions, and posting schedules
- Implemented a scheduled posting system that posts logs at configured times
- Added admin commands to manage logs and schedules
- Added a user-facing command for submitting draft logs anonymously
1. Run the schema update script to create the necessary database tables
2. Use `/setup_draft_logs` to configure a channel for posting logs
3. Add posting schedules with `/add_log_schedule`
4. Add backup logs with `/add_backup_log`
5. Test user submissions with `/submit_draft_log`
6. Test immediate posting …

initial draft log functionality

---

cogs/draft_logs_cog.py
models/draft_logs.py
update_schema.py

Enhanced draft log submission with cube name and record tracking, plus automatic retrieval of recent drafts.
- Added optional `cube` and `record` parameters to `/add_backup_log` and `/submit_log` commands
- Modified `/submit_log` to work without a URL by automatically finding the user's most recent draft
- Added automatic W-L record calculation when submitting recent drafts
- Updated log display to show cube name and record in the embed
- Added new database columns to `backup_logs` and `user_submissions` tables
- Made the URL field nullable in the `user_submissions` table
- Enhanced success messages to include cube, record, and draft time information
1. Try `/submit_log` without parameters to see if it finds your most recent draft
2. Use `/submit_log` with the new optional parameters:
- …

Draft Log post will now submit most recent log if no args included

---

cube_views/CubeSelectionView.py
views.py

- Moved `CubeUpdateSelectionView` class from `views.py` to a new dedicated module `cube_views/CubeSelectionView.py`
- Created an empty `__init__.py` in the `cube_views` directory to make it a proper Python package
- Updated imports in `views.py` to reference the new location of `CubeUpdateSelectionView`
This refactoring improves code organization by:
- Separating cube-related view logic into its own module
- Reducing the size of `views.py` which was becoming quite large
- Making the codebase more modular and easier to maintain
- Following the principle of separation of concerns
- The functionality remains exactly the same, just moved to a new location
- All existing cube selection features should continue to work as before

refactor for cleanliness

---

.gitignore
config.py
views.py

- Added a new `TEST_MODE_ENABLED` flag in `config.py` to control test features
- Added a new "Add Test Users" button that appears only when `TEST_MODE_ENABLED` is True
- Implemented `add_test_users_callback` function that adds 9 test users with long names to test UI limits
- Added `card_analysis_cache/` to `.gitignore` to prevent cache files from being committed
- Test users are only accessible to server administrators
- Each test user gets a unique ID starting from 900000000000000000
- For staked drafts, test users get random stake amounts between 50-200
- Test users are marked with a 🧪 emoji in the participants list
- Original users are preserved and marked with 👤 emoji
- The feature is disabled by default and can be enabled via config
- Test users can only be added before teams are …

add test users function

---

views.py

- Added new helper functions to handle Discord's 1024 character limit per embed field:
- `split_content_for_embed`: Splits content into chunks that fit within Discord's limits
- `add_links_to_embed_safely`: Safely adds links to embeds, splitting into multiple fields if needed
- Improved draft link display by:
- Splitting links into team-specific fields (Red/Blue)
- Adding team emojis (🔴/🔵) for better visual organization
- Shortening link text to save characters
- Enhanced sign-ups field handling:
- Automatically splits long sign-up lists into multiple fields
- Properly handles continuation fields with standardized naming
- Cleans up old continuation fields before adding new ones
These changes address several issues:
- Prevents Discord's 1024 character limit from truncating important …

split links into 2 buckets to avoid 1024 character limit

---

draft_organization/stake_calculator.py
views.py

Changed the stake capping algorithm to use the highest bet on the minimum team instead of a theoretical maximum calculation.
- Modified the stake capping algorithm in `calculate_stakes()` to use the highest bet on the minimum team as the cap for maximum team bets
- Previously, we calculated a "theoretical maximum" based on the formula: `min_team_total - ((min_team_count - 1) * min_stake)`
- Now, we simply find the highest bet on the minimum team and use that as the cap
- Updated the explanation generation in `views.py` to reflect this new approach in the UI
1. Create a draft with uneven betting between teams
2. Verify that maximum team bets are capped at the highest minimum team bet
3. Check that the explanation text correctly describes the new capping approach
4. Confirm that the …

adjustment to bet logic for proportional approach

---

modals.py

Fixed a bug in the session configuration logic for custom cube selection.
Updated the cube choice logic in `configure_session_details` to properly handle custom cube selections. Instead of checking if the `cube_choice` attribute exists, the code now explicitly checks if the cube choice is "custom" to determine whether to use the input value or the preset choice.
1. Create a session with a custom cube and verify the cube name is correctly saved
2. Create a session with a preset cube and verify the preset name is correctly saved
3. Test both premade and custom session types to ensure the cube selection works in both scenarios
The previous implementation had a logic error where it was checking for the existence of an attribute rather than the actual value of the selection. This could lead to …

fix to custom cube input  in normal servers

---

services/draft_setup_manager.py
views.py

Added detailed logging for session stage checks to improve debugging of draft seating issues.
Enhanced logging in the draft setup manager by adding more specific log messages when `check_session_stage_and_organize()` is called from different locations:
- Added context to the log message in `on_session_users` when reaching expected user count
- Added a new log message when checking session stage from `on_session_users` during cooldown checks
- Added a log message in `keep_connection_alive` when checking session stage
- Added more context to the log in `update_status_message_after_user_change`
- Added logging in `views.py` for both staked and normal draft scenarios in the `randomize_teams_callback`
1. Create a draft session and observe the logs
2. Test different scenarios that trigger …

more logging for session stage

---

services/draft_setup_manager.py

Updated logger call from string to proper info method in the keep_connection_alive function.
Changed a direct string assignment to the logger (`self.logger("check session stage...")`) to use the proper logging method (`self.logger.info("check session stage...")`). This ensures that log messages are properly formatted and categorized with the correct log level.
1. Run the application and observe the logs when the keep_connection_alive function executes
2. Verify that log messages appear correctly with the proper INFO level
3. Check that the message "check session stage from keep connection alive for user count >= expected user count" appears in logs when the condition is met
This fixes an incorrect logger usage pattern. The previous code was treating the logger as a function rather than an …

bug fix for logger

---

views.py

Disabled automatic session cleanup after 30 minutes and moved cleanup logic to execute after teams are successfully created.
- Commented out the call to `cleanup_ready_check` in the `ready_check_callback` method
- Commented out the entire `cleanup_ready_check` method that was previously set to clean up sessions after 30 minutes
- Added explicit session cleanup code in the `randomize_teams_callback` method that removes the session data immediately after teams are successfully created
1. Initiate a draft session and complete the ready check
2. Verify that the session remains active indefinitely until teams are created
3. Create teams using the randomize teams function
4. Confirm that the session data is properly cleaned up after team creation
5. Check logs for the message "✅ Teams created - …

remove timeout for Discord ready check

---

services/draft_setup_manager.py

Added a check to prevent session stage verification when expected user count is zero.
Modified the condition in `keep_connection_alive` method to only check session stage when both:
1. We have enough users (`self.users_count >= self.expected_user_count`)
2. The expected user count is not zero (`self.expected_user_count != 0`)
1. Create a draft session with expected user count set to 0
2. Monitor the connection alive functionality
3. Verify that the session stage verification is skipped when expected user count is 0
4. Test with non-zero expected user counts to ensure normal behavior is maintained
This fixes a logical issue where the system would attempt to verify session stages when the expected user count is zero, which could lead to unnecessary database checks or incorrect session state …

fix to check user count

---

services/draft_setup_manager.py
utils.py

Improved draft log collection reliability and fixed Discord bot integration issues.
- Modified the draft log collection process to use a delayed schedule (60 seconds) to ensure all data is available
- Fixed Discord bot integration by using the global bot instance instead of relying on the client property
- Changed the pick timer setting from 60 seconds to 1 second for faster drafts
- Reordered the log unlocking process to happen after posting victory/draw messages to ensure proper sequence
1. Run a draft and verify logs are collected properly after completion
2. Check that Discord embeds are sent to the appropriate channels
3. Verify that the pick timer is set to 1 second during draft setup
4. Confirm that victory/draw messages appear in results channels with proper log links
The previous …

fix for race condition on log collection and posting victory message

---

services/draft_setup_manager.py

Updated the pick timer value in draft settings from 1 second to 60 seconds.
Changed the `setPickTimer` parameter from 1 to 60 in the `update_draft_settings` method of the draft setup manager. This increases the time players have to make their draft picks from 1 second to 60 seconds.
1. Initialize a draft setup
2. Verify that the pick timer is set to 60 seconds
3. Confirm that players have 60 seconds to make their selections during the draft
The previous 1-second timer was too short for players to make meaningful draft decisions. The 60-second timer provides a more reasonable timeframe for players to evaluate their options and make strategic picks during the draft process.

revise picktimer after testing

---

datacollections.py
services/draft_setup_manager.py

Raw log should be unnecessary as it is less human readable, and is not desired for users.

remove raw log

---

services/draft_setup_manager.py
views.py

Improved the ready check experience with a countdown timer and better message handling.
- Added a countdown timer that shows when the ready check will timeout
- Enhanced ready check messages with bell emojis for better visibility
- Implemented automatic cleanup of timeout messages when ready check completes or times out
- Fixed the ready check timeout message to include instructions for users
- Added bot instance setting in the team randomization callback to ensure Discord messaging works properly
1. Start a draft and trigger a ready check
2. Verify the countdown timer appears showing when the ready check will expire
3. Let a ready check timeout and confirm the timeout message includes instructions
4. Complete a ready check successfully and verify the timeout message is deleted
5. Test …

add timer message to draftmancer ready check

---

views.py

Updated the Active role assignment logic to always assign the role when it exists, regardless of activity tracking settings.
- Modified the `update_last_draft_timestamp` function to always assign the Active role to players after a draft, as long as the role exists in the guild
- Removed the dependency on the `activity_tracking_enabled` setting for role assignment
- Clarified comments to better reflect the updated behavior
- Maintained the database update functionality which still respects the activity tracking setting
1. Create a draft session with players
2. Create an "Active" role (or whatever is configured as `active_role` in the config)
3. Complete the draft
4. Verify that all players in the draft receive the Active role, even if activity tracking is disabled in the config
This change …

fix to active role

---

services/draft_setup_manager.py

Improved WebSocket connection reliability with retry mechanism and better error handling.
- Added a new `connect_with_retry` method that implements exponential backoff for WebSocket connections
- Enhanced logging to include the WebSocket URL for easier debugging
- Simplified the draft completion logic by removing unnecessary time tracking and focusing on log collection status
- Improved error handling during connection attempts with specific error type detection
1. Initiate a draft connection that might fail initially (can be simulated with network interruption)
2. Verify that the connection is retried automatically with increasing delays
3. Check logs to confirm improved error reporting and connection status updates
4. Verify that drafts properly disconnect after logs are collected …

fix for not connecting to session properly

---

bot.py
services/draft_setup_manager.py

Enhances the draft connection system with retry logic and increases the leaderboard refresh delay to ensure proper initialization.
- Increased the leaderboard refresh delay from 30 to 120 seconds to ensure the bot is fully ready before refreshing
- Implemented a new `connect_with_retry` method with exponential backoff for more reliable websocket connections
- Simplified the draft completion logic by removing unnecessary time tracking and focusing on log collection status
- Added better error handling and logging for websocket connections to help with debugging
1. Start the bot and verify it waits the full 120 seconds before refreshing leaderboards
2. Create a draft and observe the connection logs to ensure retry logic works properly
3. Complete a draft and verify the bot properly …

fix for draftlog

---

bot.py

Fix draft reconnection task creation by using the appropriate method based on task type.
Modified the `monitor_reconnection_tasks` function to create the appropriate task based on the `task_type` parameter:
- For "setup" tasks, it continues to use `manager.keep_connection_alive()`
- For other task types, it now uses `manager.keep_draft_session_alive()`
1. Test draft reconnection with different task types:
- Verify "setup" tasks use the connection alive method
- Verify other task types use the draft session alive method
2. Check logs to confirm the correct tasks are being created
3. Ensure draft sessions remain active after reconnection
The previous implementation was using the same method (`keep_connection_alive()`) for all task types, which was incorrect. Different task types require …

fix to draft log collection

---

cogs/draft_control.py

Added a new `/release_draft_logs` command that allows draft participants to vote on releasing draft logs early.
- Created a new `LogReleaseVoteView` class that handles the voting UI and logic for releasing draft logs
- Added a global `ACTIVE_LOG_RELEASE_VOTES` dictionary to track ongoing votes
- Implemented the `/release_draft_logs` slash command that:
- Verifies the command is used in an active draft channel
- Creates a voting interface with "Yes" and "No" buttons
- Pings all draft participants to vote
- Automatically releases logs if more than half of participants vote "Yes"
- Times out after 90 seconds if not enough votes are collected
1. Start a draft with multiple participants
2. During the draft, have any participant use the `/release_draft_logs` command
3. Verify that all …

add /relase_draft_log command

---

views.py

Updated error message when a user interacts with an expired ready check.
Changed the error message in the `handle_vote` method from "Session data is missing." to "No Active Ready Check." when a user tries to interact with a session that no longer exists.
1. Start a ready check in Discord
2. Wait for the ready check to expire or be completed
3. Try to interact with the expired ready check buttons
4. Verify the new error message "No Active Ready Check." appears
The new error message is more user-friendly and clearly communicates that the ready check they're trying to interact with is no longer active, rather than suggesting there's a technical issue with missing session data.

adjust error message for clarity

---

views.py

Added a check to prevent auto team creation when queue size changes during voting.
Modified the `handle_vote` function to verify that the number of sign-ups matches the expected queue size before auto-creating teams. If the queue size has changed during voting (people joining or leaving), the system now aborts the auto team creation process and sends a notification message to the channel.
1. Start a draft session with a specific queue size (6 or 8)
2. Have users vote to fire
3. During voting, have someone leave or join the queue
4. Verify that when votes reach the threshold, the system sends the abort message instead of creating teams
5. Check that the message correctly displays the current number of people in the queue
This prevents teams from being created with an incorrect number of …

fix potentail error if someone joins/leaves queue during ready check

---

views.py

Simplified button disabling logic for the "create rooms pairings" button.
Removed conditional logic that was checking if `draft_session_id` exists in `ACTIVE_MANAGERS` before enabling the "create rooms pairings" button. Now the button is always enabled regardless of whether the draft session is active or not.
This change affects two locations:
- In the `_apply_stage_button_disabling` method
- In the `create_teams_handler` function
1. Start a draft session
2. Verify that the "create rooms pairings" button is enabled regardless of the draft session's active status
3. Ensure the button functions correctly when clicked
The previous implementation was unnecessarily disabling the "create rooms pairings" button when a draft session was active. This change simplifies the logic and ensures the …

always create rooms button works

---

views.py

Always enable the "Create Rooms" button regardless of active manager status.
Simplified the button disabling logic in three locations by removing the conditional check that was disabling the "Create Rooms" button when a draft session ID was in the `ACTIVE_MANAGERS` list. Now the button will always be enabled when it should be visible.
1. Start a draft session
2. Verify that the "Create Rooms" button is always enabled, regardless of whether the draft session ID is in `ACTIVE_MANAGERS`
3. Test the button functionality to ensure it still works correctly
The previous implementation was preventing users from creating rooms when a manager was active, which was likely causing confusion. This change ensures the button is consistently available when needed, improving the user experience by …

always allow create rooms button

---

config.py
views.py

Enabled test mode and fixed race conditions in team creation process to prevent multiple simultaneous team creation attempts.
- Enabled `TEST_MODE_ENABLED` flag in config.py
- Added a global `PROCESSING_TEAMS_CREATION` dictionary to track ongoing team creation processes
- Moved the "Add Test Users" button to be available in all session types when test mode is enabled
- Completely refactored the `randomize_teams_callback` function to:
- Check if teams are already being created for a session
- Verify the user is in the sign-up queue before allowing team creation
- Use proper response deferring for longer operations
- Add proper error handling and cleanup of processing flags
- Fix race conditions by using a global lock mechanism
1. Verify that the test button appears in all session types …

update randomize teams callback to avoid race and improper button presses

---

cube_views/CubeSelectionView.py
helpers/utils.py
modals.py

Added Powerslax cube to the available cube options.
- Added "Powerslax" as a new cube option in the dropdown selection menus across multiple files
- Added the Powerslax thumbnail image URL to the cube images dictionary
1. Start a new draft session and verify "Powerslax" appears in the cube selection dropdown
2. Create a new session and select "Powerslax" to confirm the correct thumbnail image appears
3. Verify the Powerslax option appears in all relevant selection menus
To expand the available cube options for users by adding the Powerslax cube, giving players more variety and options when selecting cubes for their draft sessions.

add powerslax cube

---

helpers/utils.py

Updated the Discord image URL for the Powerslax cube.
Changed the Discord image URL for the Powerslax cube in the `CUBE_THUMBNAILS` dictionary from a JPG format to a PNG format.
1. Run the application and navigate to where cube thumbnails are displayed
2. Verify that the Powerslax cube displays the correct PNG image
3. Ensure the image loads properly without any broken links
The new PNG image likely provides better quality or a more appropriate visual representation for the Powerslax cube. This update ensures users see the intended image when interacting with this cube.

update powerslax thumbnail

---

config.py
services/draft_setup_manager.py

Enable test mode and implement session ownership management for DraftBot to maintain control of draft sessions.
- Enabled test mode in the configuration
- Added session ownership tracking and management:
- Added properties to track connection status, session owner, and non-bot users
- Implemented periodic reconnection for when no users are present (every 5 minutes)
- Added logic to detect when DraftBot is not the session owner and request ownership
- Fixed a bug where a user joining during an active ready check was incorrectly logged as leaving
- Improved session stage checking to only run when in "teams" stage
- Added immediate draft info fetching upon connection
- Fixed logic for status message updates to only post when in "teams" stage
1. Start a draft session and verify DraftBot …

more robust draft manager connections

---

services/draft_setup_manager.py

Simplified the draft setup manager by removing the periodic reconnection and session ownership management functionality.
- Removed the periodic reconnection mechanism that would reconnect every 5 minutes when no non-bot users were present
- Eliminated session ownership tracking and the related functionality that would request crown transfer to DraftBot
- Fixed a variable name bug in the ready check logic (renamed `left_users` to `joined_users`)
- Simplified the logic for checking expected user count and seating order
- Added a handler for the 'storedSessionSettings' event
- Removed the requirement to fetch draft info on connection
- Improved conditional logic for checking session stage and organizing seating
1. Create a new draft session and verify that users can join and leave normally …

revert prior draft manager changes

---

cube_views/CubeSelectionView.py
helpers/utils.py
modals.py

Added PowerSam cube to the available cube selection options.
- Added "PowerSam" as a new cube option in the dropdown selection menus in three files:
- `CubeSelectionView.py`
- `modals.py` (in two different select menus)
- Added PowerSam's thumbnail image URL to the cube images dictionary in `helpers/utils.py`
1. Start a new draft or sealed session
2. Verify that "PowerSam" appears in the cube selection dropdown
3. Select PowerSam and confirm the correct thumbnail image appears
To expand the available cube options for users by adding the new PowerSam cube to the platform.

add powersam cube

---

cogs/draft_logs_cog.py
modals.py
sessions/staked_session.py

Updated draft logs schedule and standardized staked draft minimum to 20 tickets.
- Changed draft logs posting schedule from twice daily (10am ET / 1pm ET) to once daily at 9am
- Set a fixed minimum stake of 20 tickets for all staked drafts
- Removed the minimum stake input field from the staked draft modal
- Refactored the staked draft modal to only show when needed
- Updated the staked session description to reflect the 20/50 bet tiers (removed mention of 10 tix bets)
- Added a separate handler function for staked draft sessions
1. Verify draft logs are posted at 9am daily
2. Start a staked draft and confirm the minimum stake is set to 20 tickets
3. Check that the staked draft modal no longer shows the minimum stake input field
4. Verify the staked session description correctly shows the …

all staked drafts have 20 tix min now

---

config.py
league.py
sessions/base_session.py
utils.py
views.py

Replace hard-coded test guild ID with configurable timeout system for better maintainability and flexibility.
The codebase had the test guild ID `1229863996929216686` hard-coded across 4 files with manual timeout exemptions:
- **utils.py**: Skip cleanup entirely for test guild  
- **sessions/base_session.py**: 7 days vs 3 hours for session deletion
- **views.py**: Skip deletion_time reset on signup (2 locations)
- **league.py**: 7 days vs 6 hours for challenge deletion
This approach was inflexible, hard to maintain, and made it difficult to configure different timeout behaviors for other guilds.
Implemented a comprehensive configurable timeout system using the existing guild configuration infrastructure:
- Added `timeouts` section to default guild configuration with sensible defaults
- …

refactor hardcoded guild id reference into config

---

cube_views/CubeSelectionView.py
modals.py

Updates the 2025 MOCS Vintage Cube reference to use the correct CubeCobra URL.
- Updated `modals.py`: Changed APR25 to 3txn8 in both CubeDraftSelectionView and StakedCubeDraftSelectionView dropdown options
- Updated `cube_views/CubeSelectionView.py`: Changed APR25 to 3txn8 in CubeUpdateSelectionView dropdown options
The bot uses cube codes as identifiers in dropdown menus, which are then used to construct CubeCobra URLs dynamically using the pattern `https://cubecobra.com/cube/list/{cube_code}`.
**Before**: `https://cubecobra.com/cube/list/APR25`  
**After**: `https://cubecobra.com/cube/list/3txn8`
- `modals.py` (2 locations)
- `cube_views/CubeSelectionView.py` (1 location)
Users selecting "2025 MOCS Vintage Cube" from any draft creation dropdown will now be directed to the correct …

update the mocs cube link

---

views.py

Updates the ready check functionality to allow ready checks for any number of players 6 or above, removing the previous restriction that limited ready checks to exactly 6, 8, or 10 players.
This was a requested feature to improve draft management flexibility. Previously, if a draft had an odd number of players (like 7 or 9), users couldn't perform a ready check to verify attendance. This forced organizers to either wait for more players or kick someone without knowing if everyone was actually present.
- **Updated `views.py:750`**: Changed condition from `if sign_up_count not in (6,8,10):` to `if sign_up_count < 6:`
- **Updated error message**: Changed from "Ready check only available with 6, 8, or 10 players" to "Ready check only available with 6 or more players"
This change enables …

remove restriction on ready check
